apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cicd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-cicd-app
  template:
    metadata:
      labels:
        app: spring-cicd-app
    spec:
      containers:
        - name: spring-cicd
          image: devamber/spring-cicd:8d5c09d
          #imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
